version: '3.5'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    container_name: postgres-server
    env_file:
      - config.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    container_name: jwt_app
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: